import os
from ultralytics import YOLO

def main():
    # Load a pretrained model (YOLOv8n)
    model = YOLO("yolov8n.pt")
    
    print("Starting training on SCTD_YOLO dataset...")
    # Train the model
    # Note: We use SCTD_YOLO/data.yaml generated by voc2yolo.py
    results = model.train(
        data="SCTD_YOLO/data.yaml", 
        epochs=100, 
        imgsz=640,
        device=0, # Use GPU
        project="sonar_detection",
        name="yolov8n_sonar",
        exist_ok=True
    )
    
    print("Training finished. Evaluating and printing mAP...")
    
    # Evaluate model performance on the validation set
    metrics = model.val()
    print(f"mAP50-95: {metrics.box.map}") # mAP50-95
    print(f"mAP50: {metrics.box.map50}")  # mAP50
    
    print("Exporting the best model to ONNX format...")
    
    # Export the best model to ONNX format for Phase 2 (CPU inference)
    # The best weights are saved in sonar_detection/yolov8n_sonar/weights/best.pt
    best_model = YOLO("sonar_detection/yolov8n_sonar/weights/best.pt")
    export_path = best_model.export(format="onnx")
    
    print(f"Exported successfully to: {export_path}")
    print("Phase 1 complete! best.pt and best.onnx are ready for inference.")

if __name__ == '__main__':
    main()
